site_name: ANNUBeS
site_description: Training Artificial Neural Networks to Uncover Behavioral Strategies in neuroscience
theme:
  name: material
strict: true

theme:
  name: 'material'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: orange
    toggle:
      icon: material/weather-sunny
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: orange
    toggle:
      icon: material/weather-night
      name: "Switch to light mode"
  features:
    - announce.dismiss
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    logo: 'material/library-outline'
    next: fontawesome/solid/angle-right
    previous: fontawesome/solid/angle-left
    repo: fontawesome/brands/github-alt
    view: material/eye
  favicon: 'mouse.png'

repo_url: https://github.com/ANNUBS/annubes
repo_name: ANNUBS/annubes
edit_uri: edit/main/docs/

extra:
  version:
    provider: mike