name: linting
on:
  push:
    paths-ignore:
      # specific folder locations
      - ".vscode/**"
      - "docs/**"
      # filetypes
      - "**.md"
      - "**.rst"
      - "**.ipynb"
      - "**.cff"
      - "**.png"
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      # specific folder locations
      - ".vscode/**"
      - "docs/**"
      # filetypes
      - "**.md"
      - "**.rst"
      - "**.ipynb"
      - "**.cff"
      - "**.png"

jobs:
  lint:
    name: Linting build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Upgrade pip, install dependencies and the package
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .[dev,publishing]
      - name: Check style against standards using ruff
        run: |
          ruff check
          ruff format --check
